prefix_filename='c0';
nRepeats  = 10;
discountFactor = 0.95;

type_methods = [...
    TYPE_METHOD.THRESHOLD ,...
    TYPE_METHOD.REGULAR ,...
    TYPE_METHOD.SAP_GRP, ...
    TYPE_METHOD.SAP_GRP_LOOKAHEAD, ...
    TYPE_METHOD.SAP_NOGRP ...
%     TYPE_METHOD.DQN ,...
%     TYPE_METHOD.DDQN ,...
%     TYPE_METHOD.QLEARNING ,...
%     TYPE_METHOD.SALSA ,...
%     TYPE_METHOD.THRESHOLD, ...
%     TYPE_METHOD.REGULAR, ...
%     TYPE_METHOD.SAP_GRP ...
    ];

fix_mains = [0,10,50,200,300]; %th rocks
% fix_main = 10; %th rocks
% fix_main = 50; %th rocks
% fix_main = 200; %th rocks
% fix_main = 300; %th rocks



module_multiple_experiments(mySetting,methods,prefix_filename, setting);