function type_methods = use_methods_with_different_iter(base_niter)
if nargin<1
    base_niter = 100;
end

%% ADJUSTED TARGETING 2 Hours for Pole
% type_methods = { ...
%     {TYPE_METHOD.SAC_NOGRP, 2*base_niter} ...
%     {TYPE_METHOD.TD3,6*base_niter} ...
%     {TYPE_METHOD.PPO_DACT,2*base_niter*3*14} ...
%     {TYPE_METHOD.AC_DACT,base_niter*2*12*4} ...
%     {TYPE_METHOD.PG_DACT,base_niter*2*15*4} ...
%     {TYPE_METHOD.DDQN ,base_niter*2*2*3} ... % Previously existing
%     {TYPE_METHOD.DQN ,base_niter*2*2*3} ... % Previously existing
%     };
type_methods = { ...
    {TYPE_METHOD.THRESHOLD ,base_niter}...
    {TYPE_METHOD.PERIODICAL ,base_niter}...
    {TYPE_METHOD.DO_NOTHING,base_niter} ...
    {TYPE_METHOD.MAINTAIN_EVERYTIME,base_niter} ...
    {TYPE_METHOD.DDQN ,base_niter*2*2} ... % Previously existing
    {TYPE_METHOD.DQN ,base_niter*2*2} ... % Previously existing
    {TYPE_METHOD.SAC_NOGRP_LOOKAHEAD, base_niter} ...
    {TYPE_METHOD.SAC_GRP_LOOKAHEAD, base_niter} ...
    {TYPE_METHOD.SAC_GRP, base_niter} ...
    {TYPE_METHOD.SAC_NOGRP, base_niter} ...
    {TYPE_METHOD.TRPO_DACT_CSTA, base_niter} ...
    {TYPE_METHOD.DDPG, base_niter} ...
    {TYPE_METHOD.TD3,base_niter} ...
    {TYPE_METHOD.PPO_DACT,2*base_niter*3} ...
    {TYPE_METHOD.AC_DACT,base_niter*2*12} ...
    {TYPE_METHOD.PG_DACT,base_niter*2*15} ...
    };