function type_methods = use_methods_temporary_list()

% ORIGINAL METHODS
type_methods = [...
%     TYPE_METHOD.SAC_GRP_LOOKAHEAD, ...
%     TYPE_METHOD.SAC_GRP, ...
    TYPE_METHOD.SAC_NOGRP ...
    TYPE_METHOD.DQN ,...
    TYPE_METHOD.DDQN ,...
    TYPE_METHOD.QLEARNING ,...
    TYPE_METHOD.SALSA ,...
    ];

%     %% ALL RL METHODS
%     type_methods = [...
%         TYPE_METHOD.SAC_GRP_LOOKAHEAD, ...
%         TYPE_METHOD.SAC_GRP, ...
%         TYPE_METHOD.SAC_NOGRP, ...
%         TYPE_METHOD.TRPO_DACT_CSTA,...
%         TYPE_METHOD.TRPO_CACT_CSTA_SAC_ACTOR,...
%         TYPE_METHOD.TRPO_CACT_CSTA,...
%         TYPE_METHOD.TD3,...
%         TYPE_METHOD.PPO_CACT_SAC_ACTOR,...
%         TYPE_METHOD.PPO_CACT,...
%         TYPE_METHOD.PPO_DACT,...
%         TYPE_METHOD.DDPG,...
%         TYPE_METHOD.AC_CACT_SAC_ACTOR,...
%         TYPE_METHOD.AC_CACT,...
%         TYPE_METHOD.AC_DACT,...
%         TYPE_METHOD.PG_CACT,...
%         TYPE_METHOD.PG_DACT,...
%         TYPE_METHOD.DDQN ,... % Previously existing
%         TYPE_METHOD.DQN ,... % Previously existing
%         TYPE_METHOD.QLEARNING ,... % Previously existing
%         TYPE_METHOD.SALSA ,... % Previously existing
%         TYPE_METHOD.THRESHOLD ,...
%         TYPE_METHOD.PERIODICAL ,...
%         TYPE_METHOD.DO_NOTHING,...
%         ];

    % type_methods = [...
%     TYPE_METHOD.THRESHOLD ,...
%     TYPE_METHOD.REGULAR ,...
%     TYPE_METHOD.SAC_GRP, ...
%     TYPE_METHOD.SAC_GRP_LOOKAHEAD, ...
%     TYPE_METHOD.SAC_NOGRP ...
% %     TYPE_METHOD.DQN ,...
% %     TYPE_METHOD.DDQN ,...
% %     TYPE_METHOD.QLEARNING ,...
% %     TYPE_METHOD.SALSA ,...
% %     TYPE_METHOD.THRESHOLD, ...
% %     TYPE_METHOD.REGULAR, ...
% %     TYPE_METHOD.SAC_GRP ...
%     ];

% % ORIGINAL METHODS
% type_methods = [...
% %     TYPE_METHOD.SAC_GRP_LOOKAHEAD, ...
% %     TYPE_METHOD.SAC_GRP, ...
%     TYPE_METHOD.SAC_NOGRP ...
% %     TYPE_METHOD.THRESHOLD ,...
% %     TYPE_METHOD.PERIODICAL ,...
% %     TYPE_METHOD.DQN ,...
% %     TYPE_METHOD.DDQN ,...
% %     TYPE_METHOD.QLEARNING ,...
% %     TYPE_METHOD.SALSA ,...
% %     TYPE_METHOD.THRESHOLD, ...
% %     TYPE_METHOD.REGULAR, ...
% %     TYPE_METHOD.SAP_GRP ...
%     ];
end